export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const RETRIEVE_ACCOUNTS = "RETRIEVE_ACCOUNTS";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ALL_ACCOUNTS = "DELETE_ALL_ACCOUNTS";